### ISSUE TITLE
[問題回報] 電腦版 設定介面無法正常退出

### ISSUE THREAD

**Issue by Yowoapple** [ExpTechTW/TREM#1]
### ✍🏻 描述詳細情況
* 預期效果: 點 儲存 或 取消 退出設定介面
* 實際效果: 儲存 和 取消 不工作，必須藉由完全關閉軟體，重啟軟體後才能達到退出介面效果
![image](https://user-images.githubusercontent.com/86045137/169762478-0cfee37c-ab15-416e-a8c3-1e97f4b60981.png)

### 📑 相關資訊
* 版本: [TREM 1.2]

### 👨🏻‍🔧 還有什麼我們需要知道的嗎？
* 補充說明: N/A

**Comment by whes1015** [comment]
> ### ✍🏻 描述詳細情況
> * 預期效果: 點 儲存 或 取消 退出設定介面
> * 實際效果: 儲存 和 取消 不工作，必須藉由完全關閉軟體，重啟軟體後才能達到退出介面效果
>   ![image](https://user-images.githubusercontent.com/86045137/169762478-0cfee37c-ab15-416e-a8c3-1e97f4b60981.png)
> 
> ### 📑 相關資訊
> * 版本: [TREM 1.2]
> 
> ### 👨🏻‍🔧 還有什麼我們需要知道的嗎？
> * 補充說明: N/A
> 
> #### 此檔案由 ExpTech.tw 設計製作

試試 1.3 的版本
