### ISSUE TITLE
[問題回報] Missing icons for shindo >5-

### ISSUE THREAD

**Issue by YacineBoussoufa** [ExpTechTW/TREM#43]
### ✍🏻 描述詳細情況
* 預期效果: Shindo 5-, 5+, 6-, 6+ and 7 icons are missing in the reports. 

![image](https://user-images.githubusercontent.com/46266665/190862619-5614a48a-c1c2-4f6c-83b9-7a6803a0d07b.png)

* 實際效果: Shindo icons >5- should be visible

### 📑 相關資訊
* 版本: 1.7.5, 1.8, 1.8.5

### 👨🏻‍🔧 還有什麼我們需要知道的嗎？
* 補充說明: Open an event with shindo >5-

####  此檔案由 ExpTech.tw 設計製作

P.S. You should add an english version for this template xD

**Comment by YacineBoussoufa** [comment]
Fixed in 4.9.0 version by https://github.com/ExpTechTW/TREM/commit/206bd9335885bb338e75205460d27d1f0180d45e.

**Comment by kamiya10** [comment]
English version of the bug report template added.
