### ISSUE TITLE
[問題回報] 更改設定時設定檔 JSON 機率性出錯

### ISSUE THREAD

**Issue by TimTsai0316** [ExpTechTW/TREM#44]
### ✍🏻 描述詳細情況
* 預期效果: 無錯誤
* 實際效果: 更改設定後 JSON 結尾有機會多出一個大括號導致無法解析

### 📑 相關資訊
* 版本: 4.9.0

### 👨🏻‍🔧 還有什麼我們需要知道的嗎？
* 補充說明: 更改任何設定皆有可能觸發

####  此檔案由 ExpTech.tw 設計製作

![image](https://user-images.githubusercontent.com/53219265/190871145-e1ec6a6e-29f9-43a6-a95d-80c2ea63842b.png)

**Comment by kamiya10** [comment]
可以請你提供重現這個問題的步驟以及在更改哪項設定發生這個問題的嗎？

**Comment by TimTsai0316** [comment]
發生問題的流程如下影片，另外除了深色模式選項，其他設定選項也可能觸發。
手動刪除設定檔中多餘大括號並儲存後，錯誤視窗就會消除。


https://user-images.githubusercontent.com/53219265/190884765-a41c2c7d-a4d8-49cb-bff9-427a0e2a2264.mp4

**Comment by kamiya10** [comment]
🤔
我現在還是沒有頭緒為什麼會多一個大括號
有看到可能是fs的問題: https://github.com/itinance/react-native-fs/issues/869

**Comment by kamiya10** [comment]
@TimTsai0316 可以詢問現在最新版 [v5.1.0](https://github.com/ExpTechTW/TREM/releases/tag/5.1.0) 這個問題有解決了嗎

**Comment by TimTsai0316** [comment]
@kamiya10 需要等我回去打開電腦測試，稍後更新

**Comment by TimTsai0316** [comment]
> @TimTsai0316 可以詢問現在最新版 [v5.1.0](https://github.com/ExpTechTW/TREM/releases/tag/5.1.0) 這個問題有解決了嗎

v5.1.0 更新後多次嘗試更改設定，目前沒有出現問題。

**Comment by kamiya10** [comment]
那看來是解決了
耶
