### ISSUE TITLE
[問題回報] 嘗試關閉所有最上層顯示，地震預警啟動後會持續在最上層的BUG

### ISSUE THREAD

**Issue by Yomisana** [ExpTechTW/TREM#47]
### 描述詳細情況
地震預警啟動後，當S波經過所在地後過了 一兩分鐘還不會回到原本的狀態(9成不會回到原本狀態)，需要自行手動重新啟動。
剛使用軟體沒多久，但遇到BUG回報一下，剛好遇到地震預警系統啟動後會顯示在最上層但是發現會一直強制讓TREM顯示在最上層。

### 預期效果
地震預警啟動後會不要顯示在最上層。

### 實際效果
地震預警啟動後會有類似像Timer 持續讓軟體顯示在最上層，需要將軟體重新啟動

### 重現步驟
1. 強震即時警報 eew.cover false
2. 地震報告 report.cover false
3. 即時測站 Real-time.cover false

### 版本資訊
4.9.0
Windows 10 Pro (10.0.19044)

### 還有什麼我們需要知道的嗎？
設定開關按鈕很難按 :P

**Comment by whes1015** [comment]
4.9.5 還有這個問題嗎?
另外回到原本狀態需要最後一報收到後過4分鐘才會回到原本狀態

**Comment by Yomisana** [comment]
LGTM 4.9.5
還在觀察下次的地震預警啟動後是否4分鐘後就可以回到原本狀態

**Comment by st90115** [comment]
不知道能不能新增一個選項是手動回到原本狀態？因為震波到所在地之後就想回到原本狀態確認其他情況

**Comment by Yomisana** [comment]
> LGTM 4.9.5 還在觀察下次的地震預警啟動後是否4分鐘後就可以回到原本狀態
4.9.5 還依然存在，測試報的訊息沒有回到原本的狀態
