### ISSUE TITLE
國家級警報音效過大，以及其他建議

### ISSUE THREAD

**Issue by dannyhsu21** [ExpTechTW/TREM#48]
### 描述詳細情況

(主要)國家級警報音效過大
(次要)重現過去的緊急地震速報發布時，無論所在地預測震度是否大於所設定值時，皆會有國家級警報提示音
(次要)重現過去的緊急地震速報發布時，回到一般畫面須手動重啟

### 預期效果

(主要)希望能對個別音效新增個別音量大小設定，讓使用者可自定義設定各音效音量，尤其是國家級警報，因無國家級警報的音效音量可調整
(次要)應於所在地預測震度大於等於設定值才會有國家級警報提示，小於設定值可以僅接收速報但不播放國家級警報提示音，與手機在接收國家級警報所使用體感相同
(次要)新增按鈕可結束重現按鈕或回到目前時間，可放於時間位置的旁邊

### 實際效果

(主要)在重現緊急地震速報時，連帶播放的國家級警報音效過大
(次要)於所在地接收震度設定為「5-」時，在重現緊急地震速報時，無論速報顯示的所在地震度為0、1、2、3、4時，都會有國家級警報提示音，又因音效過大容易造成地震速報提示地震過大但實際地震很小的誤解
(次要)重現過往緊急地震速報結束時，無任何按鈕可結束重現，需到右下角工具列手動重啟才可恢復正常

### 重現步驟

(主要)接收緊急地震速報自動播放過大國家級警報提示音，造成需調低程式音量
(次要)於設定>>強震即時警報>>接收震度設定於「5-」>>重現過往緊急地震速報(最大震度4以下)>>接收的速報顯示所在地預測為4以下>>軟體自動播放國家級警報音效
(次要)對過往緊急地震速報按右鍵重現，欲結束重現時介面上無任何方式可結束

### 版本資訊

4.9.5、5.0.0

### 還有什麼我們需要知道的嗎？

5.0.0版本有說明有優化「檢查更新」，但好像仍無檢查更新的按鈕或方式

**Comment by kamiya10** [comment]
多個問題請個別 issue 開

1. 音量問題 5.1.0 有個別音量設定
2. 國家級警報的音效要請 @whes1015 回答，我不確定他放這個後面的目的是什麼
3. 重現地震要重新啟動的問題會再做內部討論


檢查更新是自動檢查的
在抓去必要資料時會順便檢查 （約每十分鐘）

**Comment by whes1015** [comment]
警報音效的播放邏輯為地震造成的最大震度超過 `4級` 以上就會播放，下個版本會更改為 `5弱`，此設計是參考日本的各類速報軟體
