### ISSUE TITLE
左上資訊錯誤

### ISSUE THREAD

**Issue by sus2790** [ExpTechTW/TREM#52]
### 描述詳細情況

左上時間、PGA為NaN

### 預期效果

* 正常的顯示

### 實際效果

![image](https://user-images.githubusercontent.com/104747821/192150945-c7d16ff9-7a83-4c2a-831c-e0a678619a6c.png)

### 重現步驟

* 打開TREM

### 版本資訊

5.0.6

### 還有什麼我們需要知道的嗎？

無

**Comment by kamiya10** [comment]
已在下一個版本中修復
