### ISSUE TITLE
[建議]

### ISSUE THREAD

**Issue by sus2790** [ExpTechTW/TREM#56]
### 🌟想法補充
* 補充說明:
最近版本更新484太多了
建議全部放到6.0.0之類的

**Comment by kamiya10** [comment]
會有這麼多小更新是為了要讓整個程式變得更穩定
我們當然也可以只更新 6.0.0 
但是這樣子程式在我們發布 6.0.0 前可能會有**無法使用**的問題 （API 更動、算法改變等）

並且發布小版本是為了要解決有急迫性的問題
（像是設定檔無法儲存，CPU 佔用率過高）

我們內部開發有詳細列出在什麼版本會有什麼功能，也算是強迫我們不要把這個專案拋棄掉（又稱懶癌）。

**Comment by sus2790** [comment]
🤔 好的大佬，但TREM重置設定功能好像不會重設Webhook預設內容？

**Comment by kamiya10** [comment]
現在設定是重設會有一個預設的訊息可以讓不知道要怎麼填寫的人有一個模板可以來改
雖然後面的版本會有 GUI 可以不用跟 json 代碼對決

**Comment by sus2790** [comment]
喔喔，那就先這樣ㄅ
(蠻期待6.0.0)

**Comment by sus2790** [comment]
喔對了，可以用刪json資料的方式來還原webhook預設訊息
