### ISSUE TITLE
TREM prevents Windows to properly shutdown

### ISSUE THREAD

**Issue by YacineBoussoufa** [ExpTechTW/TREM#70]
### What happened?

While I was shutting down my PC an error occurred preventing windows 10 to properly shutdown without a human intervention.

### Expected behavior

* Windows 10 should shutdown without any error related to TREM, and without any input from the user.

### Actual behavior

* An error occurs while shutting down (blue screen "shutting down"), and Windows is unable to close the app:
![image](https://user-images.githubusercontent.com/46266665/199104382-d9337f99-6e59-4855-a09e-7c09800fde88.png)
[translation]
`An exception error has occurred, unknown software exception (0x80000003) in the application at position 0x00007FF68C45A8A5. Click "OK" to terminate the application.`

### Reproduction steps

1. Run TREM
2. Shutdown PC
3. The error occurs

### Version info

TREM 5.1.4 - Windows 10 Home (10.0.19043)

### Note

TREM is installed in the Program Files folder.
Windows 10 fast startup is disabled.
A TREM Shortcut is present in the "Automatic start up" folder.
In the Task Manager TREM appears two times in the startup tab (I don't know if it's an issue, worked fine before)
![image](https://user-images.githubusercontent.com/46266665/199105406-403ab5d2-4576-4fbf-a7b3-4cd3f181d9f4.png)

**Comment by kamiya10** [comment]
It seems like this is an issue related to electron as reported in electron/electron#34311 and electron/electron#18935
We would like to know if this is also happening on your machine without "Minimize to Tray" enabled in the settings
If the error still appears, we can have some further investigations and workarounds about the issue.

**Comment by YacineBoussoufa** [comment]
> We would like to know if this is also happening on your machine without "Minimize to Tray" enabled in the settings

It seems that the issue doesn't happen when the "Minimize to Tray" is disabled.
