### ISSUE TITLE
為什麼我打不開這個程式

### ISSUE THREAD

**Issue by dg558831** [ExpTechTW/TREM#71]

**Comment by kamiya10** [comment]
我們是人我們不會通靈
回報問題請詳細敘述你遇到了什麼問題、重現步驟、版本等資訊供我們尋找問題在哪裡
你可以在再開問題的時候選擇使用範本來用標準的問題回報格式

1. 點擊 New Issue ![image](https://user-images.githubusercontent.com/58339640/200153376-bfd76e7b-2718-4753-9a11-cd18029ea3d2.png)

2. 選擇 問題回報 ![image](https://user-images.githubusercontent.com/58339640/200153396-a87d3110-9ffb-4d3c-8cea-271e1f136a7c.png)

3. 選入相關欄位 ![image](https://user-images.githubusercontent.com/58339640/200153413-4c1f3b54-6f5e-425e-84a2-5d859a3cc6c7.png)
