### ISSUE TITLE
TREM爛掉了

### ISSUE THREAD

**Issue by sus2790** [ExpTechTW/TREM#73]
### 描述詳細情況

![image](https://user-images.githubusercontent.com/104747821/200788997-d2ac5fa5-4906-4ee0-bb04-f33984ad98c5.png)

### 預期效果

* 正常運行

### 實際效果

* 崩潰

### 重現步驟

* 正常啟動

### 版本資訊

5.1.4

### 還有什麼我們需要知道的嗎？

無

**Comment by kamiya10** [comment]
![Screenshots_2022-11-09-17-15-37.png](https://user-images.githubusercontent.com/58339640/200789694-4aea6eec-9d93-4dfc-866a-23d49b7ea779.png)
