### ISSUE TITLE
打不開

### ISSUE THREAD

**Issue by dg558831** [ExpTechTW/TREM#74]
### 描述詳細情況
點他打不開
[2022-11-13 20-12-35.zip](https://github.com/ExpTechTW/TREM/files/9997143/2022-11-13.20-12-35.zip)

### 預期效果
打開
* 

### 實際效果
沒打開
* 

### 重現步驟

1. 點他沒打開

### 版本資訊

5.1.4跟6.0.0-82-pre4
### 還有什麼我們需要知道的嗎？
無

**Comment by yayacat** [comment]
描述不夠詳細

**Comment by sus2790** [comment]
不會通靈
(至少丟一張節圖?)

**Comment by yayacat** [comment]
你寫這樣我不會通靈也不是你肚子裡的蛔蟲
