### ISSUE TITLE
Back button on event view, resizes the detail information tab instead of returning to the map view

### ISSUE THREAD

**Issue by YacineBoussoufa** [ExpTechTW/TREM#81]
### What happened?

When you click on the notification for an event, and then you click the back button the event detail information tab (i don't know how to call it) resizes instead of returning to the map view.

### Expected behavior

* The return button should return to the map view.

### Actual behaviour

* The event detail tab gets resized.

### Reproduction steps

1. Wait for an event to happen.
2. Open the notification for an event. 
3. Click the back button to return to the map.
4. The event detail tab gets resized instead of returning to the map.

### Version info

Version 6.0.0-pre.17
Windows 10 Home (10.0.19045)

### Note

a) Normal information detail tab.
![image](https://user-images.githubusercontent.com/46266665/208158243-28c8da19-0d81-4bec-ac1d-d4cbbb43552d.png)

b) Information detail tab, after clicking the back button for some time.
![image](https://user-images.githubusercontent.com/46266665/208158256-d43d923d-e44e-4317-b4d8-e8e09e5fe3fa.png)

**Comment by kamiya10** [comment]
TREM v6.0.0 is still under heavy development due to the new API format and should be fixed in the next version
