### ISSUE TITLE
無法顯示

### ISSUE THREAD

**Issue by KnowScratcher** [ExpTechTW/TREM#85]
### 描述詳細情況
開起來就只顯示這樣，跟網路上別人不同
測站無法顯示
![image](https://user-images.githubusercontent.com/103301742/212457703-d6c0cbb2-57ce-4ae1-9033-dc4fcb3feb8c.png)

### 版本資訊
v6.0.0 Beta8.0

**Comment by yayacat** [comment]
https://docs.google.com/document/d/1nNE6sOr1NQHITcVLvsot1HcM-0meM7lmrJaAr2M_Ckw/edit?usp=sharing
