### ISSUE TITLE
Power usage is unreasonably high

### ISSUE THREAD

**Issue by ChAoSUnItY** [ExpTechTW/TREM#87]
### 描述詳細情況
Power usage is unreasonably high even when TREM isn't properly receiving datas.

![image](https://user-images.githubusercontent.com/43753315/217731874-f80a09f5-4c2d-49c4-8bad-2f0a8099ccad.png)

![image](https://user-images.githubusercontent.com/43753315/217731784-c9a5389b-7df7-48ad-9c2e-254588e9d200.png)

Additionally, user's computer fan would be highly possible running unreasonably faster than normal.

### 預期效果
It should not consume that much power.

### 實際效果
It consumes lots of power usage and causes computer fan running faster than normal.

### 重現步驟
1. Enable TREM start when computer starts.
2. Open Task Manager
3. You'll see TREM's power usage is very high.

### 版本資訊
![image](https://user-images.githubusercontent.com/43753315/217732351-ccb28bd3-ec14-48bd-9d6a-d1684f78bb4f.png)

### 還有什麼我們需要知道的嗎？
Additional notice: I noticed that even when I turn off option that enables TREM starts on computer starts, it would still start.

**Comment by jasperkangYT1** [comment]
你可以下載最新版本(6.0.0 beta.8)
you can download lastest version(6.0.0 beta.8)

**Comment by whes1015** [comment]
https://github.com/ExpTechTW/TREM-Lite
